import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers"; // Import Providers (a client component)

export const metadata: Metadata = {
  title: "AgentKit Quickstart",
  description: "Generated by `create-onchain-agent`, a Next.js template for AgentKit",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 dark:bg-gray-900 dark flex flex-col min-h-screen">
        <header className="py-6 flex items-center justify-between relative">
          {/* Header */}
        </header>

        {/* Main Content */}
        <Providers>
          <main className="flex-grow flex items-center justify-center px-4">{children}</main>
        </Providers>

        {/* Footer */}
        <footer className="py-4 text-center text-gray-500 dark:text-gray-400 flex-none">
          {/* Footer */}
        </footer>
      </body>
    </html>
  );
}
